format = """
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$python\
$php\
$rust\
$golang\
$ruby\
$lua\
$package\
$docker_context\
$kubernetes\
$aws\
$azure\
$gcloud\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = 'yggdrasil'

[character]
success_symbol = "§"
error_symbol = "§"

# Directory and Git
[directory]
style = 'bold fg:pdir'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = 'δ/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'dimmed fg:gbra'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:gsta'
format = '([$all_status$ahead_behind]($style) )'

# Programming languages (sorted by popularity)
[nodejs]
style = 'njs'
symbol = '󰎙 '
format = '[$symbol($version )]($style)'

[python]
style = 'pyt'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[php]
style = 'php'
symbol = '󰌟 '
format = '[$symbol($version )]($style)'

[rust]
style = 'rus'
symbol = ' '
format = '[$symbol($version )]($style)'

[golang]
style = 'gol'
symbol = ' '
format = '[$symbol($version )]($style)'

[ruby]
style = 'rub'
symbol = ' '
format = '[$symbol($version )]($style)'

[lua]
symbol = ' '
format = '[$symbol($version )]($style)'

# Package and environment management
[package]
style = 'pkg'
symbol = '󰏗 '
format = 'δ [$symbol$version]($style) '

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[kubernetes]
symbol = '☸ '
disabled = false
detect_files = ["k8s", "kubernetes"]

# Cloud Providers
[aws]
symbol = ' '
style = 'cprovider'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[azure]
symbol = '󰠅 '
style = 'cprovider'
format = '[$symbol($subscription)]($style)'

[gcloud]
symbol = ' '
style = 'cprovider'
format = '[$symbol$account(@$domain)]($style)'

# System and performance
[jobs]
style = 'job'
symbol = ' '
format = '[$symbol]($style)'
number_threshold = 1

[cmd_duration]
style = 'fg:cmddur'
format = '[$duration]($style)'
min_time = 500

[fill]
symbol = ' '

[palettes.yggdrasil]
pdir = '#ffe169'
gbra = '#fffdf7'
gsta = '#ffe169'
njs = '#9d4edd'
pyt = '#ffea00'
php = '#118ab2'
rus = '#b5e48c'
gol = '#a2d2ff'
rub = '#56cfe1'
pkg = '#c8b6ff'
job = '#f25c54'
cprovider = '#757bc8'
cmddur = '#434C5E'